import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/Navbar";
import Appbar from "./components/Appbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} id="root">
        <Appbar/>
        <NavBar /> {/* Properly use NavBar without children */}
        <main className={`flex-grow ml-72 p-6 overflow-y-auto`}>
          {children}
        </main>
      </body>
    </html>
  );
}
